### ISSUE TITLE
[ENHANCE01] Editar informações do perfil de usuário offline

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#133]
## Descrição
Eu, como Cuidador, desejo editar meu perfil de usuário online e offline para que eu possa manter meu perfil atualizado.

Nessa tarefa, deve haver um opção na barra inferior que dê acesso ao perfil. Ao acessar o perfil, o cuidador deve conseguir editar suas informações cadastradas tanto online quanto offline.

## Critérios de Aceitação
- [ ] O usuário deve ver uma opção "Perfil" na barra inferior de navegação do aplicativo.
- [ ] Ao clicar na opção "Perfil", o usuário deve ser redirecionado para a página de perfil.
- [ ] Ao clicar no ícone de lápis, o usuário deve ser redirecionado para a página de edição de perfil.
- [ ] A página de edição de perfil deve exibir o campo para "Nome Completo" que pode ser editado.
- [ ] Ao clicar no botão "Salvar", o sistema deve validar o campo.
- [ ] Se a entrada for válida, o sistema deve salvar a mudança e exibir uma mensagem de confirmação (ex: "Perfil atualizado com sucesso").

### Tela de perfil de usuário
![image](https://github.com/user-attachments/assets/6e2d63ec-1939-4b13-932c-8e40e299992f)
