### ISSUE TITLE
[ENHANCE05] Cadastrar, visualizar, editar e apagar tarefas da rotina do idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#137]
## Descrição
Eu, como Cuidador, desejo cadastrar, visualizar, editar e apagar tarefas da rotina do idoso para que eu possa organizar a rotina do idoso.

## Critérios de Aceitação

Criação da tarefa
- [ ] Deve haver um botão "+" visível na agenda ou na tela principal de tarefas do idoso.
- [ ] Ao clicar no botão "+", o cuidador deve ser redirecionado para a tela de adicionar nova tarefa.
- [ ] A tela de adicionar nova tarefa deve incluir os seguintes campos:
- Título da Tarefa (obrigatório)
- Descrição da Tarefa (opcional)
- Horário e Data (obrigatório)
- Opção de Repetição (sim/não) e seleção de Dias da Semana (aparecer somente se a opção de repetição for marcada como "sim")
- Categoria (opcional)
- [ ] Deve haver um botão "Cancelar" que permite ao cuidador sair da tela de adição de tarefa sem salvar.
- [ ] Deve haver um botão "Salvar" que permite ao cuidador salvar a nova tarefa.
- [ ] Ao clicar em "Salvar", o sistema deve validar todas as entradas obrigatórias.
- [ ] Ao abrir uma tarefa já cadastrada, deve haver a opção para "Excluir" a tarefa.
- [ ] Ao clicar em "Excluir", o sistema deve pedir confirmação antes de remover a tarefa permanentemente.
- [ ] Só poderá criar uma nova tarefa caso tenha um idoso cadastrado, caso não tenha deve aparecer uma mensagem sugerindo cadastrar um idoso.

Visualização da tarefa
- [ ] Deve haver uma  tela principal de "Rotina" acessível na barra de navegação do cuidador.
- [ ] No topo dessa tela, deve haver ícones representando cada idoso sob o cuidado do cuidador.
- [ ] Ao clicar no ícone de um idoso, a agenda diária deve atualizar para mostrar as tarefas cadastradas especificamente para aquele idoso.
- [ ] O ícone do idoso selecionado deve ser destacado para indicar qual idoso está sendo visualizado no momento.
- [ ] A agenda diária deve exibir todas as tarefas cadastradas para o idoso selecionado no formato de uma lista no calendário diário.
- [ ] Cada tarefa deve ser exibida com seu título, descrição e horário.
- [ ] Deve ser possível navegar através dos dias da agenda.
- [ ] Deve haver a opcao de editar tarefa.

 

### Tela de cadastro de tarefas
![image](https://github.com/user-attachments/assets/b4cce362-2372-45cf-af5d-c31134a3f211)
![image](https://github.com/user-attachments/assets/8b2c4ddc-7444-4dbe-bdf7-8f0e3c653109)
