### ISSUE TITLE
[US02] Recuperar senha

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#52]
## Descrição
Eu, como Cuidador, desejo recuperar minha senha para que eu possa fazer login na plataforma, caso perca o acesso a senha cadastrada.

Nessa tarefa, deve haver um botão de esqueci minha senha na tela de login, ao clicar neste botão o usuário é encaminhado para uma tela onde informará seu email para que receba um link. Ao clicar neste link será encaminhado para uma tela onde será possível cadastrar a nova senha. 

## Pré-requisitos
* #53 

## Critérios de Aceitacao
- [x] Deve haver a opção "Esqueci minha senha" na tela de login.
- [x] Ao clicar no botão "Esqueci minha senha", o usuário deve ser redirecionado para uma tela onde poderá informar seu email.
- [x] A tela de recuperação de senha deve incluir um campo para o usuário inserir seu email.
- [x] Deve haver um botão "Enviar" na tela de recuperação de senha.
- [x] Se o campo de email estiver vazio ou não contiver um formato de email válido, uma mensagem de erro apropriada deve ser exibida (ex: "Por favor, insira um email válido").
- [ ] Ao inserir um email válido e clicar em "Enviar", o sistema deve enviar um email para o endereço fornecido.
- [ ] O email deve conter um link para a página de redefinição de senha.
- [x] A tela de redefinição de senha deve incluir campos para "Nova Senha" e "Confirmar Nova Senha".
- [x] Os campos de senha devem seguir a política de segurança (ex: mínimo de 8 caracteres, pelo menos uma letra maiúscula, uma minúscula, um número e um caractere especial).
- [x] Deve haver um botão "Redefinir Senha".
- [x] Se a validação for bem-sucedida, a nova senha deve ser salva e o usuário deve ser notificado com uma mensagem de confirmação (ex: "Sua senha foi redefinida com sucesso").
- [x] Se houver erros na validação, mensagens de erro apropriadas devem ser exibidas.

### Tela inicial
![image](https://github.com/user-attachments/assets/62518d6f-54bc-4380-a883-6f85d02d22bb)
* A tela de cadastro de nova senha será adicionada no protótipo

**Comment by AmandaNbr** [comment]
- Adicionar a sincronizaçao do `user`
- Refatorar o banco pra ficar igual o banco do serviço de `user`
- Fazer estratégia de login (logar de fato)
- Adicionar testes e testes retroativos
