### ISSUE TITLE
[US01] Login no aplicativo

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#53]
## Descrição
Eu, como Cuidador, desejo me registrar à plataforma para que eu possa ter acesso às funcionalidades do sistema.

Nessa tarefa, ao entrar no aplicativo do GEROcuidado, o cuidador terá a opção de cadastrar-se. Essa opção o levará para uma tela de cadastro onde nessa tela estará disponível alguns campos para inserir os dados. Além disso há também o caso do cuidador já possuir um cadastro, sendo levado então para a tela de login. Essa tela necessita apenas do e-mail e da senha para acessar a conta.

## Pré-requisitos
Nenhum

## Critérios de Aceitação

- [ ] O usuário deve ser capaz de acessar a página de cadastro a partir da página inicial.
- [ ] O formulário de cadastro deve incluir campos para inserir o nome completo, email e a senha.
- [ ] O campo de senha deve ter uma política de segurança (mínimo de 8 caracteres).
- [ ] Deve aparecer uma mensagem informando caso a senha cadastrada seja "forte" ou "fraca".
- [ ] O usuário deve ser capaz de enviar o formulário de cadastro clicando em um botão "Cadastrar".
- [ ] Após um cadastro bem-sucedido, o usuário deve ser redirecionado para a página inicial.
- [ ] O usuário deve ser capaz de acessar a página de login a partir da página inicial.
- [ ] O formulário de login deve incluir campos para inserir o email e a senha.
- [ ] O usuário deve ser capaz de enviar o formulário de login clicando em um botão "Login".
- [ ] O sistema deve verificar se o email e a senha correspondem a uma conta registrada.
- [ ] Se o email ou a senha estiverem incorretos, o sistema deve exibir uma mensagem de erro apropriada.
- [ ] Se o email e a senha estiverem corretos, o usuário deve ser redirecionado para a página do painel principal.
- [ ] O campo de senha deve ocultar os caracteres digitados.

### Tela inicial
![image](https://github.com/user-attachments/assets/c67272a4-ed12-4fd3-b668-e005c437f8b6)

### Tela de cadastro
![image](https://github.com/user-attachments/assets/e1bee351-93de-4dd4-9899-2bac694dda1b)

### Tela de login
![image](https://github.com/user-attachments/assets/fd6f1aa1-74a5-4d5e-9a54-131aeb4ebdd0)

## Tarefas

TO-DO: Tarefas em issues que devem ser feitas no repo de desenvolvimento @ubrando
