### ISSUE TITLE
[US03] Editar perfil de usuário

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#54]
## Descrição
Eu, como Cuidador, desejo editar meu perfil de usuário para que eu possa manter meu perfil atualizado.

Nessa tarefa, deve haver um opção na barra inferior que dê acesso ao perfil. Ao acessar o perfil, o cuidador deve conseguir editar suas informações cadastradas.

## Pré-requisitos
* #53 

## Critérios de Aceitação
- [ ] O usuário deve ver uma opção "Perfil" na barra inferior de navegação do aplicativo.
- [ ] Ao clicar na opção "Perfil", o usuário deve ser redirecionado para a página de perfil.
- [ ] Ao clicar no ícone de lápis, o usuário deve ser redirecionado para a página de edição de perfil.
- [ ] A página de edição de perfil deve exibir os campos para "Nome Completo", "Email" e "Senha" que podem ser editados.
- [ ] Ao clicar no botão "Salvar", o sistema deve validar todas as entradas.
- [ ] Se todas as entradas forem válidas, o sistema deve salvar as mudanças e exibir uma mensagem de confirmação (ex: "Perfil atualizado com sucesso").
- [ ] Se houver erros na validação, o sistema deve exibir mensagens de erro apropriadas sem salvar as mudanças.
- [ ] O campo "Senha" deve ter uma política de segurança (ex: mínimo de 8 caracteres, pelo menos uma letra maiúscula, uma minúscula, um número e um caractere especial).

### Tela de perfil de usuário
![image](https://github.com/user-attachments/assets/6e2d63ec-1939-4b13-932c-8e40e299992f)
