### ISSUE TITLE
[US04] Cadastrar perfil de idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#55]
## Descrição
Eu, como Cuidador, desejo cadastrar perfis de idosos para que eu possa registrar informações, métricas e tarefas da rotina dos idosos cuidados.

Nessa tarefa, o cuidador deve ser capaz de cadastrar um novo idoso com as informações necessárias.

## Pré-requisitos
* #53 

## Critérios de Avaliação

- [ ] Ao acessar o perfil o deve haver a opção "Idosos", ao clicar nessa opção o usuário deve ser redirecionado a página de gerenciar idosos
- [ ] A página de gerenciar idosos deve listar todos os idosos já cadastrados, permitindo editar as informações deles.
- [ ] Deve haver um botão "Cadastrar um idoso", ao clicar nesse botão o usuário deve ser redirecionado a página de cadastro de idosos.
- [ ] A tela de cadastro deve incluir os seguintes campos: Nome Completo (obrigatório), Data de Nascimento (obrigatório), Tipo sanguíneo, Número de telefone (obrigatório) e um campo livre para observações.
- [ ] Todos os campos obrigatórios devem ser validados para garantir que não estão vazios.
- [ ] O campo "Data de Nascimento" deve validar se a data inserida é uma data válida e no formato correto.
- [ ] O campo "Número de telefone" deve validar que o telefone está em um formato válido.
- [ ] Deve haver um botão "Salvar" na tela de cadastro, ao clicar em "Salvar", o sistema deve validar todas as entradas.
- [ ] Se todas as entradas forem válidas, o sistema deve salvar as informações do idoso e exibir uma mensagem de confirmação (ex: "Perfil do idoso cadastrado com sucesso").
- [ ] Após um cadastro bem-sucedido, o cuidador deve ser redirecionado para a página de gerenciar idosos.

### Tela de cadastro de idosos
![image](https://github.com/user-attachments/assets/812ebc4a-5fc6-406e-8cf5-1ece35022892)

## Tarefas

- [x] #78 
- [ ] Tela de listagem de idosos 
- [ ] Tela de cadastro de idosos 
- [ ] Criar os modelos no banco de dados 
  - [ ] Criar o schema do banco de dados
  - [ ] Criar a migração do idoso
