### ISSUE TITLE
[US05] Cadastrar medicamentos e alimentos no perfil do idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#56]
## Descrição
Eu, como Cuidador, desejo cadastrar remédios e alimentos no perfil do idoso para que eu possa ter essas informações salvas e com fácil acesso.

Nessa tarefa, o cuidador deve ser capaz de registrar alimentos e remédios associados a um idoso.

## Pré-requisitos
* #55

## Critérios de aceitação
- [ ] A tela de cadastro ou edição do perfil do idoso deve incluir dois campos livres: Um campo para "Medicamentos"; Um campo para "Alimentacao".
- [ ] Esses campos devem permitir a entrada de texto livre para que o cuidador possa listar remédios e alimentos conforme necessário.
- [ ] Os campos podem ser opcionais, permitindo que o cuidador deixe-os vazios se não houver informações a serem cadastradas.
- [ ] Deve haver um botão "Salvar" na tela de cadastro ou edição.
- [ ] Ao clicar em "Salvar", o sistema deve validar todas as entradas e salvar as informações inseridas, e exibir uma mensagem de confirmação (ex: "Perfil do idoso atualizado com sucesso").
- [ ] Após um cadastro ou edição bem-sucedido, o cuidador deve ser redirecionado para a lista de perfis de idosos cadastrados.
- [ ] Ter uma "info" nos campos de Alimentacao e Medicamentos explicando que e apenas uma descricao em texto livre. Nao tem relacao com outras funcionalidades.

### Tela de cadastro de idosos
![image](https://github.com/user-attachments/assets/d6d7c0a4-0c56-40f6-8d54-d34dde8aaf3c)
*Os campos de alimento e remédio serão adicionados no protótipo

**Comment by AmandaNbr** [comment]
- Atualizar protótipo
- Fazer as dívidas tecnicas e resolver bugs
- Realizar testes e testes retroativos
- Sincronização do serviço do idoso
