### ISSUE TITLE
[US06] Cadastrar tarefas da rotina do idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#57]
## Descrição
Eu, como Cuidador, desejo cadastrar tarefas da rotina do idoso para que eu possa organizar a rotina do idoso.

Nessa tarefa, o cuidador deve ser capaz de cadastrar tarefas na agenda.

## Pré-requisitos
* #55

## Critérios de Aceitação

- [ ] Deve haver um botão "+" visível na agenda ou na tela principal de tarefas do idoso.
- [ ] Ao clicar no botão "+", o cuidador deve ser redirecionado para a tela de adicionar nova tarefa.
- [ ] A tela de adicionar nova tarefa deve incluir os seguintes campos:
- Título da Tarefa (obrigatório)
- Descrição da Tarefa (opcional)
- Horário e Data (obrigatório)
- Opção de Repetição (sim/não) e seleção de Dias da Semana (aparecer somente se a opção de repetição for marcada como "sim")
- Categoria (opcional)
- [ ] Deve haver um botão "Cancelar" que permite ao cuidador sair da tela de adição de tarefa sem salvar.
- [ ] Deve haver um botão "Salvar" que permite ao cuidador salvar a nova tarefa.
- [ ] Ao clicar em "Salvar", o sistema deve validar todas as entradas obrigatórias.
- [ ] Ao abrir uma tarefa já cadastrada, deve haver a opção para "Excluir" a tarefa.
- [ ] Ao clicar em "Excluir", o sistema deve pedir confirmação antes de remover a tarefa permanentemente.
- [ ] Só poderá criar uma nova tarefa caso tenha um idoso cadastrado, caso não tenha deve aparecer uma mensagem sugerindo cadastrar um idoso.

### Tela de cadastro de tarefas
![image](https://github.com/user-attachments/assets/b4cce362-2372-45cf-af5d-c31134a3f211)

**Comment by AmandaNbr** [comment]
- Fazer sincronização com o serviço
- Fazer testes
