### ISSUE TITLE
[US07] Visualizar as tarefas da rotina de um idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#58]
## Descrição
Eu, como Cuidador, desejo conseguir visualizar as tarefas da rotina do idoso para que eu possa saber o que deverá ser realizado no dia de hoje.

Nessa tarefa, o cuidador deve ser capaz de enxergar as tarefas do idoso no formato de agenda diária. Cada tarefa com seu título.

## Pré-requisitos
* #57

## Critérios de Aceitação

- [ ] Deve haver uma  tela principal de "Rotina" acessível na barra de navegação do cuidador.
- [ ] No topo dessa tela, deve haver ícones representando cada idoso sob o cuidado do cuidador.
- [ ] Ao clicar no ícone de um idoso, a agenda diária deve atualizar para mostrar as tarefas cadastradas especificamente para aquele idoso.
- [ ] O ícone do idoso selecionado deve ser destacado para indicar qual idoso está sendo visualizado no momento.
- [ ] A agenda diária deve exibir todas as tarefas cadastradas para o idoso selecionado no formato de uma lista no calendário diário.
- [ ] Cada tarefa deve ser exibida com seu título, descrição e horário.
- [ ] Deve ser possível navegar através dos dias da agenda.
- [ ] Deve haver a opcao de editar tarefa.

### Visualização de tarefas
![image](https://github.com/user-attachments/assets/8b2c4ddc-7444-4dbe-bdf7-8f0e3c653109)

* Add botao de editar tarefa
