### ISSUE TITLE
[US08] Marcar as tarefas como concluídas ou não

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#59]
## Descrição
Eu, como Cuidador, desejo marcar tarefas como realizadas para que eu possa saber quais tarefas foram cumpridas.

Nessa tarefa, o cuidador deve ser capaz de marcar as tarefas da agenda do idoso como feitas.

## Pré-requisitos
* #57

## Critérios de Aceitação

- [ ] Na tela de visualização das tarefas, cada tarefa deve ter um checkbox ao lado do título para indicar se a tarefa foi realizada ou não.
- [ ] O cuidador deve poder marcar o checkbox ao lado de uma tarefa para indicá-la como concluída.
- [ ] Ao marcar o checkbox, a tarefa deve ser visualmente diferenciada (ícone de checkmark).
- [ ] O estado de conclusão da tarefa (marcada ou não) deve ser persistente. Se o cuidador sair da tela ou fechar o aplicativo e depois retornar, a tarefa deve manter o status atualizado.

### Tela de agenda/calendário
![image](https://github.com/user-attachments/assets/13d2fbb0-072d-4ed3-98e1-22918d9f9fbc)
