### ISSUE TITLE
[US09] Cadastrar métricas de um idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#60]
## Descrição
Eu, como Cuidador, desejo cadastrar as métricas de saúde do usuário para que eu possa manter um histórico clínico do idoso.

Nessa tarefa, o cuidador deverá ser capaz de registrar as métricas do idoso para uma determinada data. As métricas deverão ser persistidas na base de dados do aplicativo.

## Pré-requisitos
* #55

## Critérios de Aceitação
- [ ] Deve haver uma opção "Métricas" acessível na barra inferior da aplicação.
Ao clicar na opção "Métricas", o cuidador deve ser redirecionado para uma tela onde pode visualizar as métricas do idoso.
- [ ] Deve haver um botão "+" na tela de métricas para adicionar novas métricas.
- [ ] Ao clicar no botão "+", o cuidador deve ser redirecionado para a tela de cadastro de métricas.
- [ ] A tela de cadastro de métricas deve incluir categorias predefinidas para escolha, tais como:
- Sinais Vitais
- Nutrição
- Atividade
Com sub-categorias, por exemplo, ao selecionar "Sinais Vitais", deve haver campos específicos para:
- Frequência Cardíaca
- Pressão Arterial
- Glicemia
- Temperatura Corporal
- Saturação de Oxigênio
- [ ] Deve haver um campo para a data e hora atuais, preenchidos automaticamente, mas editáveis se necessário.
- [ ] Todos os campos de métricas devem permitir apenas entradas válidas (ex: numéricas para frequência cardíaca, pressão, glicemia, etc.).
- [ ] Deve haver validação para garantir que os campos obrigatórios não estejam vazios.
- [ ] Deve haver um botão "Cancelar" que permite ao cuidador sair da tela de cadastro de métricas sem salvar.
- [ ] Deve haver um botão "Salvar" que permite ao cuidador salvar as métricas inseridas.
- [ ] Ao clicar em "Salvar", o sistema deve validar todas as entradas obrigatórias.
- [ ] Se todas as entradas forem válidas, o sistema deve salvar as métricas e exibir uma mensagem de confirmação (ex: "Métricas cadastradas com sucesso").
- [ ] Após um cadastro bem-sucedido, o cuidador deve ser redirecionado para a tela de visualização das métricas do idoso.

### Tela de métricas

![image](https://github.com/user-attachments/assets/0f113a25-9afd-4bb8-9708-25bdaabfcde4)
