### ISSUE TITLE
[US11] Gerar relatório das métricas do idoso

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#61]
## Descrição
Eu, como Cuidador, desejo gerar um relatório das métricas do idoso para que eu possa salvar as métricas de um determinado período e mantê-la de fácil acesso.

Nessa tarefa, o usuário deve ser capaz de fazer download de um relatório de métricas durante determinado intervalo de tempo.

## Pré-requisitos
* #60

## Critérios de Aceitação

- [ ] Na tela de métricas, deve haver um botão visível para "Gerar Relatório".
Tela de Geração de Relatório:
- [ ] Ao clicar no botão "Gerar Relatório", o cuidador deve ser redirecionado para uma tela onde pode configurar as opções do relatório.
- [ ] A tela de geração de relatório deve incluir:
- Opções de métricas que podem ser selecionadas para inclusão no relatório (ex: sinais vitais, nutrição, atividade).
- Campos de data de início e fim para definir o intervalo de tempo das métricas incluídas no relatório.
- [ ] O relatório deve ser gerado em formato PDF para facilitar o download e a impressão.
- [ ] O PDF deve incluir as métricas selecionadas, organizadas por categoria e ordenadas cronologicamente dentro do intervalo de tempo especificado.
- [ ] Após a geração do relatório em PDF, o cuidador deve ter a opção de compartilhar ou fazer o download do relatório para salvar localmente.

### Telas de métricas
![image](https://github.com/user-attachments/assets/9b347310-d3c8-431f-b95e-b3e42c5aa338)
*Será adicionado uma opção de gerar relatório das métricas
