### ISSUE TITLE
[US12] Participar do fórum

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2024-1-GEROcuidado-Doc#62]
## Descrição
Eu, como Cuidador, desejo participar do Fórum de cuidadores para que eu possa compartilhar e consumir informações

Nessa tarefa, o cuidador deve ser capaz de interagir com o fórum de cuidadores, realizando posts e interagindo.

## Pré-requisitos
* #53

## Critérios de Aceitação
- [ ] Deve haver uma opção "Fórum" acessível na barra inferior da aplicação.
- [ ] Ao clicar na opção "Fórum", o cuidador deve ser redirecionado para uma página web dedicada ao fórum.
- [ ] Deve ser possível criar novas postagens.

### Fórum usuários cadastrados

![image](https://github.com/user-attachments/assets/95090c99-05de-49cc-bafb-9638a00f76db)>
