### ISSUE TITLE
[US14] Ter acesso a um f.a.q (dúvidas frequentes) sobre o aplicativo

### ISSUE THREAD

**Issue by GustaaSZ** [fga-eps-mds/2024-1-GEROcuidado-Doc#64]
## Descrição
Eu, como Cuidador, desejo ter acesso a um f.a.q (dúvidas frequents) sobre o aplicativo para que eu possa esclarecer dúvidas comuns a respeito do aplicativo.

Nessa tarefa, o cuidador deve ser capaz de acessar o f.a.q do aplicativo para esclarecer possíveis dúvidas.

## Pré-requisitos
Nenhum

## Critérios de Aceitação
- [ ] Deve haver uma botão de "FAQ" claramente acessível no perfil do usuário dentro do aplicativo.
- [ ] O FAQ deve abordar questões comuns e suas respostas relacionadas ao uso do aplicativo.
- [ ] As questões frequentes podem incluir temas como funcionalidades principais, como resolver problemas comuns, e informações gerais sobre o uso do aplicativo.
- [ ] As perguntas e respostas no FAQ devem estar organizadas de forma lógica e categorizada, facilitando a navegação e a busca por informações específicas.
Deve ser possível navegar rapidamente entre diferentes seções do FAQ para encontrar respostas relevantes.

## Protótipo
*O protótipo do f.a.q será adicionado em breve
