### ISSUE TITLE
[US15] Tutorial explicativo do aplicativo no primeiro acesso

### ISSUE THREAD

**Issue by GustaaSZ** [fga-eps-mds/2024-1-GEROcuidado-Doc#65]
## Descrição
Eu, como Cuidador, desejo ter acesso a um tutorial que demonstre as funcionalidades do aplicativo durante meu primeiro acesso, para que eu possar obter uma visão geral do que consigo realizar.

Nessa tarefa, o cuidador deve ser capaz de visualizar um tutorial que demonstre as funcionalidades do aplicativo.

## Pré-requisitos
* #53

## Critérios de Aceitação

- [ ] Após o login inicial do cuidador, deve ser exibido automaticamente um tutorial de slides que demonstre as principais funcionalidades e recursos do aplicativo.
- [ ] Os slides devem apresentar de forma visual e clara as funcionalidades essenciais do aplicativo.
- [ ] Cada slide deve abordar uma funcionalidade específica, com uma breve descrição e uma imagem ilustrativa ou captura de tela.
- [ ] Deve haver controles de navegação simples nos slides, como botões "Próximo" e "Pular tutorial", para permitir que o cuidador avance ou pule o tutorial.

### Tela de visualização do tutorial

Protótipo em desenvolvimento.
