### ISSUE TITLE
[US10] Visualizar as métricas cadastradas de forma visual com gráficos e dashboards

### ISSUE THREAD

**Issue by marcellaanderle** [fga-eps-mds/2024-1-GEROcuidado-Doc#66]
## Descrição
Eu, como Cuidador, desejo visualizar as métricas cadastradas de forma visual (gráficos, dashboard) para que eu possa interpretar melhor, mais facilmente e com mais rapidez as métricas cadastradas.

Nessa tarefa, o usuário deve ser capaz de acessar as métricas cadastradas e vizualizá-las.

## Pré-requisitos
* #60

## Critérios de Aceitação

- [ ] Ao clicar na opção "Métricas" na barra inferior da aplicação, o cuidador deve ser redirecionado para uma tela onde pode visualizar as métricas agrupadas registradas do idoso.
- [ ] Cada agrupamento deve exibir uma média das métricas relevantes para aquela categoria, quando aplicável.
- [ ] Ao clicar em alguma métrica agrupada, o cuidador deve ser redirecionado para uma tela detalhada que mostre um histórico de registros da métrica para aquela categoria.
- [ ] O histórico deve ser apresentado de forma clara e organizada, mostrando datas e valores registrados ao longo do tempo.

### Telas de métricas
![image](https://github.com/user-attachments/assets/8d87f60a-6f98-4456-ba60-2ce2d7d8402c)
