### ISSUE TITLE
Configurar Infraestrutura microserviço APIUsuarios

### ISSUE THREAD

**Issue by VictorJorgeFGA** [fga-eps-mds/2024-1-GEROcuidado-Doc#97]
É necessário configurar a infraestrutura do microserviço da API de Usuarios.

- [x] O microserviço deve estar disponível para consumo do aplicativo
- [x] O microserviço deve estar disponível no dockerhub para atualização e deploy
- [x] O microserviço deve utilizar a containerização configurada no repositório
